### ISSUE TITLE
Convert repo to Tonel

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Mocketry#14]
Our Exercism project is referencing this githhub repo of Mocketry. 
When loading I get a **filename or extension is too long** error 
with Windows Pharo 7.0.3, https://github.com/exercism/pharo-smalltalk/issues/328

Can this repo be converted to Tonel?

**Comment by bencoman** [comment]
PR https://github.com/dionisiydk/Mocketry/pull/15

**Comment by dionisiydk** [comment]
Done in v5.0.0
