### ISSUE TITLE
Loading Mocketry with Core group loads tests of dependencies

### ISSUE THREAD

**Issue by jecisc** [dionisiydk/Mocketry#20]
I wanted to load the 'Core' group of Mocketry to limit the amount of code I load in some project but doing so still loads the tests of StateSpecs and Ghost. 

Maybe the granularity of the groups could be reworked so that we can avoid to load the tests of the dependencies when we do not load the tests of Mocketry?

**Comment by dionisiydk** [comment]
Hi @jecisc .

It is known bug of Metacello. But author does not consider it as a bug. See discussion here https://github.com/Metacello/metacello/issues/472.

You can check baselines of Mocketry and dependencies. They all clearly define that Core depends on Core of dependencies and should not include any tests.

**Comment by dionisiydk** [comment]
Looking deeply at baselines I found my mistake. So it will be fixed in upcoming release.
(Not sure if it is related to my Metacello issue because I used simpler projects in that case).

**Comment by jecisc** [comment]
Thanks a lot! 
I added to my todo list to check the Metacello bug, but if it works without it it's even better since I don't have much time to check!

**Comment by jecisc** [comment]
Hi, @dionisiydk

I can confirm that loading Mocketry core does not load the tests of StateSpecs and Ghost anymore.

Thank you!

**Comment by jecisc** [comment]
(using v6.0.x)
