### ISSUE TITLE
Question around mock setup - how to pass mock instances to inst. vars?

### ISSUE THREAD

**Issue by Bajger** [dionisiydk/Mocketry#37]
Hi Denis! @dionisiydk 
As part of my activities on Exercism project, where your Mocketry library is used, I have some question around running code with mock instances:
I want to have following statement (simplified):
```
testExecuteDownloading

	| cmd exercise  mockHttpClient mockReader baseUrl  |
	
	Any strictMocks: false.
	mockHttpClient := ExercismHttpClient asMock.
	mockReader := TonelReader asMock.

	[  
	cmd := (ExercismDownloadCommand
		from: mockHttpClient track: 'pharo' exercise: 'test-exercise')
		yourself.
	
	exercise := cmd execute. "tonel reader used in this code"
	
	self assert: exercise notNil description: 'Get a result'.
	
	sourceCode := exercise contentsFor: 'test1.st' ifAbsent: [''].
	self assert: sourceCode equals: 'Some source1'
	
	] runWithMockSetup: [  
	
		
	mockHttpClient expect verifyToken atLeastOnce.
	"... + some other stub sessages for mockClient"
		
	(mockReader expect loadDefinitions) willReturnYourself.
	].
```
Code above is kind-of integration test, that execution is done properly (I have some more dedicated unit tests on objects/classes used in command execution). 
Problem is that **I don't know how to stub just certain instance side method of TonelReader that is used in code of execution of command above**. TonelReader is instantiated as one of local variables of method executed on other object of download command (so it is internal implementation that shouldn't be really exposed as part of command interface).

Should I just stub constructor method (class side) of TonelReader class that would return an instance of TonelReader mock (with dedicated stub instance side method)?

Thanks much for your answer!
David

**Comment by Bajger** [comment]
I've resolved it by stubbing the constructor of tonel reader class. Closing this issue.

**Comment by dionisiydk** [comment]
Sorry @Bajger . I missed the notification.

Stubbing a class is a possible approach. But IMHO it indicates/drives the change in the design. 
I would refactor a command to have a reader and a client as an instance variables and then the test will be much simpler.

Anyway I am not familiar with Mocketry extensions from the Exercism project (and in readme here you will not find used expressions). So I don't understand all details.
