### ISSUE TITLE
Cannot load v7.0.x revspec as dependency of my baseline project

### ISSUE THREAD

**Issue by Bajger** [dionisiydk/Mocketry#39]
I've tried to define dependency for P11, P12 using:
```
spec
    	baseline: 'Mocketry'
    	with: [ spec repository: 'github://dionisiydk/Mocketry:v7.0.x' ].
```
See: https://github.com/exercism/pharo-smalltalk/actions/runs/7871570770/job/21475121571#step:4:100 

Also tried to load manually: 
```
Metacello new
  baseline: 'Mocketry';
  repository: 'github://dionisiydk/Mocketry:v7.0.x';
  load
```
But I have "Revspec v7.0.x not found" error. Am I doing something wrong here?

**Comment by dionisiydk** [comment]
I added the branch v7.0.x. Please try again

**Comment by Bajger** [comment]
Thanks! I thought just tagging a commit with a version is enough, I didn't know that version branch must exist!
